gallery/urls.py
from __future__ import absolute_import
"""virtualization URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

from django.conf.urls import url
from django.contrib import admin
from .views import Gallery, GalleryPhotoUploadView, GalleryItemView

urlpatterns = [
    url(r'^list$', Gallery.as_view(), name="gallery-list"),
    url(r'^upload$', GalleryPhotoUploadView.as_view(), name="gallery-upload"),
    url(r'^item/(?P<pk>[\w]+)/$', GalleryItemView.as_view(), name='gallery-detail'),
]

virtualization/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='gallery:gallery-list')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include("gallery.urls", namespace="gallery")),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.six import python_2_unicode_compatible
# Create your models here.
from gallery.utils import detect_labels


@python_2_unicode_compatible
class GalleryItem(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255, blank=True)
    image = models.ImageField()
    tags = models.ManyToManyField("GalleryTag", through="ItemTag")


    def save(self, *args, **kwargs):
        super(GalleryItem, self).save(*args, **kwargs)
        labels = detect_labels(self.image.file)
        for label in labels:
            name = label['Name']
            confidence = label['Confidence']
            gallery_tag, created = GalleryTag.objects.get_or_create(name=name)
            ItemTag.objects.create(item=self, tag=gallery_tag, confidence=confidence)

    def __str__(self):
        return "{} - {}".format(self.name, self.image)


@python_2_unicode_compatible
class ItemTag(models.Model):
    item = models.ForeignKey("GalleryItem", related_name="item_tags")
    tag = models.ForeignKey("GalleryTag")
    confidence = models.FloatField()

    def __str__(self):
        return "{} - {} - {}".format(self.item, self.tag, self.confidence)


@python_2_unicode_compatible
class GalleryTag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return "{}".format(self.name)

gallery/forms.py
from django import forms

from gallery.models import GalleryItem


class GalleryItemUploadForm(forms.ModelForm):
    class Meta:
        model = GalleryItem
        fields = (
            'image',
            'name',
        )

gallery/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views.generic import TemplateView, CreateView, ListView, DetailView

from gallery.forms import GalleryItemUploadForm
from gallery.models import GalleryItem
from gallery.utils import find_similar_images


class Gallery(ListView):
    template_name = "gallery/gallery.html"
    model = GalleryItem

    def get_queryset(self):
        qs = super(Gallery, self).get_queryset()
        qs = qs.order_by('-created')
        return qs


class GalleryPhotoUploadView(CreateView):
    form_class = GalleryItemUploadForm
    template_name = 'gallery/upload.html'

    def get_success_url(self):
        return reverse('gallery:gallery-list')


class GalleryItemView(DetailView):
    template_name = "gallery/image.html"
    model = GalleryItem

    def get_context_data(self, **kwargs):
        ctx = super(GalleryItemView, self).get_context_data(**kwargs)
        ctx['similar_items'] = find_similar_images(self.get_object())
        return ctx

gallery/templates/gallery/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Gallery</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<div class="container">
    {% block content %}


    {% endblock %}

</div>
</body>
</html>

gallery/templates/gallery/gallery.html
{% extends "gallery/base.html" %}

{% block content %}
    <div class="row">
        <ul class="nav navbar-nav">
            <li>
                <a href="{% url "gallery:gallery-upload" %}">Upload image</a>

            </li>
        </ul>

    </div>
    <h3>Gallery:</h3>
    <ul>
        {% for gallery_item in object_list %}
            <a href="{% url "gallery:gallery-detail" pk=gallery_item.pk %}"><img src="{{ gallery_item.image.url }}"
                                                                                 alt=""
                                                                                 height="100"
                                                                                 width="100"
            ></a>
            <ol>
                {% for tag_item in gallery_item.item_tags.all %}
                    <li>{{ tag_item.tag.name }} - {{ tag_item.confidence }}</li>
                {% endfor %}
            </ol>
        {% endfor %}

    </ul>

{% endblock %}

gallery/templates/gallery/image.html
{% extends "gallery/base.html" %}

{% block content %}
    <div class="row">
        <ul class="nav navbar-nav">
            <li>
                <a href="{% url "gallery:gallery-list" %}">All images</a>

            </li>
            <li>
                <a href="{% url "gallery:gallery-upload" %}">Upload image</a>

            </li>
        </ul>

    </div>
    <h3>
        Image:
    </h3>
    <img src="{{ object.image.url }}" alt=""
         height="100"
         width="100"
    >
    {% for tag_item in object.item_tags.all %}
        <li>{{ tag_item.tag.name }} - {{ tag_item.confidence }}</li>
    {% endfor %}
    <br>
    <div class="well">
        Similar images
    </div>
    <ul>
        {% for similarity, similar_item in similar_items %}
            <a href="{% url "gallery:gallery-detail" pk=similar_item.pk %}"><img src="{{ similar_item.image.url }}"
                                                                                 alt=""
                                                                                 height="100"
                                                                                 width="100"
            ></a>
            {% for tag_item in similar_item.item_tags.all %}
                <li>{{ tag_item.tag.name }} - {{ tag_item.confidence }}</li>
            {% endfor %}
            <strong>Similarity: {{ similarity }}</strong>
            <br>
        {% endfor %}

    </ul>

{% endblock %}

gallery/templates/gallery/upload.html
{% extends "gallery/base.html" %}

{% block content %}
    <div class="row">
        <ul class="nav navbar-nav">
            <li>
                <a href="{% url "gallery:gallery-list" %}">List images</a>

            </li>
        </ul>

    </div>
    <form enctype="multipart/form-data" action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.image.id_for_label }}">Email address</label>
            <input type="file" name="{{ form.image.name }}" class="form-control" id="{{ form.image.id_for_label }}"
                   placeholder="Upload file">
        </div>
        <input type="submit" class="btn btn-primary" value="Upload file"/>
    </form>
{% endblock %}